ALTER TABLE insights ADD COLUMN expectation_basis TEXT NOT NULL DEFAULT 'MODEL_PROPOSED';
ALTER TABLE insights ADD COLUMN causal_status TEXT NOT NULL DEFAULT 'CAUSAL_HYPOTHESIS';
ALTER TABLE insights ADD COLUMN validation_status TEXT NOT NULL DEFAULT 'UNTESTED';
ALTER TABLE insights ADD COLUMN identification_status TEXT NOT NULL DEFAULT 'NOT_IDENTIFIED';
ALTER TABLE insights ADD COLUMN causal_context TEXT;
