import { readFileSync } from "node:fs";
import { expect, test, type Page } from "@playwright/test";
import type dictionary from "../public/locales/en.json";
type Dictionary = typeof dictionary;
const en = JSON.parse(readFileSync(new URL("../public/locales/en.json", import.meta.url), "utf8")) as Dictionary;
const ja = JSON.parse(readFileSync(new URL("../public/locales/ja.json", import.meta.url), "utf8")) as Dictionary;
const fixture = new URL("./fixtures/analysis.csv", import.meta.url).pathname;
async function noOverflow(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
}

test("required fields, errors, CSV preview and deterministic report in both locales and sizes", async ({ page }, info) => {
  const t = info.project.use.locale === "ja" ? ja : en;
  await page.goto("/");
  await page.locator("#new-project").click();
  const name = page.locator("#new-project-name");
  await expect(name).toBeFocused();
  await expect(name).toHaveAttribute("aria-invalid", "true");
  await expect(name).toHaveAttribute("required", "");
  await page.getByRole("alert").getByRole("link").click();
  await expect(name).toBeFocused();
  await noOverflow(page);
  await name.fill("UX " + info.project.name);
  await name.press("Enter");
  await expect(page).toHaveURL(/\/input$/);
  await page.getByRole("button", { name: t["project.addDocument"] }).click();
  const content = page.locator("#paste-content");
  await expect(content).toBeFocused();
  await expect(content).toHaveAttribute("aria-describedby", /paste-content-hint.*paste-content-example.*paste-content-error/);
  await expect(page.locator("#paste-title")).not.toHaveAttribute("required");
  await noOverflow(page);
  await content.fill("An interview note.");
  await page.getByRole("button", { name: t["project.addDocument"] }).click();
  await page.getByRole("link", { name: new RegExp(t["nextStep.analysis.action"]) }).click();
  await expect(page.locator("#run-analysis")).toBeDisabled();
  await expect(page.locator("#analysis-start-help")).toContainText(t["readiness.noModelNoDataset"]);
  await page.getByRole("link", { name: t["readiness.fixDataset"] }).click();
  await expect(page.locator('input[name="import-kind"][value="documents"]')).toBeChecked();
  await expect(page.getByRole("radio", { name: t["input.format.analysis.title"] })).not.toBeVisible();
  const download = page.waitForEvent("download");
  await page.getByRole("link", { name: new RegExp(t["input.format.template"]) }).click();
  expect(readFileSync(await (await download).path(), "utf8")).toBe("id,source,title,content\n");
  const other = page.getByText(t["input.csv.otherFormats"]);
  await other.focus(); await other.press("Enter");
  await page.getByRole("radio", { name: t["input.format.analysis.title"] }).check();
  await page.getByLabel(t["project.csvFile"]).setInputFiles(fixture);
  const preview = page.getByRole("region", { name: t["input.preview.title"] });
  await expect(preview).toContainText(t["input.preview.confirmHint"]);
  await expect(preview).toContainText("corporate_number is empty");
  await noOverflow(page);
  await preview.getByRole("button", { name: t["project.importAnalysisData"] }).click();
  await expect(page.getByText(t["input.csv.importedNext"])).toBeVisible();
  await page.getByRole("link", { name: new RegExp(t["nextStep.analysis.action"]) }).click();
  await expect(page.locator("#run-analysis")).toBeEnabled();
  await page.locator("#run-analysis").click();
  await page.getByRole("link", { name: new RegExp(t["analysisPage.viewResults"]) }).click();
  const report = page.waitForEvent("download");
  await page.getByRole("link", { name: t["project.downloadReport"] }).first().click();
  expect(readFileSync(await (await report).path(), "utf8").length).toBeGreaterThan(100);
  await noOverflow(page);
  await page.emulateMedia({ reducedMotion: "reduce" });
  expect(await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue("--transition-fast").trim())).toMatch(/^0(?:ms|s)$/);
});

test("UNKNOWN settings remain distinct and defaults follow selected values", async ({ page }, info) => {
  const t = info.project.use.locale === "ja" ? ja : en;
  const p = await (await page.request.post("/api/projects", { data: { name: "Unknown settings" } })).json() as { id: string };
  await page.request.post(`/api/projects/${p.id}/documents`, { data: { source: "web", content: "Research note." } });
  await page.route("**/api/settings", (route) => route.fulfill({ status: 503, json: { error: "temporarily unavailable" } }));
  await page.goto(`/#/projects/${p.id}/analysis`);
  await expect(page.locator("[data-readiness]")).toHaveAttribute("data-readiness", "unknown");
  await expect(page.locator("#run-analysis")).toBeEnabled();
  await page.getByText(t["analysis.advancedSettings"]).click();
  await page.locator("#research-question").fill("A specific question");
  await page.locator("#output-locale").selectOption("en-US");
  await page.getByText(t["analysis.advancedSettings"]).click();
  await expect(page.getByText(/A specific question/)).toBeVisible();
  await expect(page.locator("form > p")).toContainText(t["outputLocale.enUS"]);
  await noOverflow(page);
});
