package usecase

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"insight-lab/internal/domain"
	"insight-lab/internal/service"
)

// ProjectReport is a portable, human-readable snapshot of the latest
// analysis. Keeping report assembly in the use-case layer lets HTTP remain a
// delivery concern and makes future PDF/export adapters reuse the same data.
type ProjectReport struct {
	Project     *domain.Project
	Documents   map[string]*domain.Document
	Insights    []*InsightDetail
	Metrics     *service.Metrics
	GeneratedAt time.Time
}

func (a *Application) ExportProjectMarkdown(ctx context.Context, projectID string) ([]byte, error) {
	project, err := a.repos.Projects.Get(ctx, projectID)
	if err != nil {
		return nil, err
	}
	documents, err := a.repos.Documents.ListByProject(ctx, projectID)
	if err != nil {
		return nil, fmt.Errorf("list report documents: %w", err)
	}
	insights, err := a.repos.Insights.ListByProject(ctx, projectID)
	if err != nil {
		return nil, fmt.Errorf("list report insights: %w", err)
	}

	details := make([]*InsightDetail, 0, len(insights))
	for _, insight := range insights {
		detail, err := a.GetInsight(ctx, insight.ID)
		if err != nil {
			return nil, fmt.Errorf("build report insight %s: %w", insight.ID, err)
		}
		details = append(details, detail)
	}

	var metrics *service.Metrics
	if analysis, err := a.repos.Analyses.LatestByProject(ctx, projectID); err == nil && analysis.Metrics != "" {
		var parsed service.Metrics
		if json.Unmarshal([]byte(analysis.Metrics), &parsed) == nil {
			metrics = &parsed
		}
	}
	documentIndex := make(map[string]*domain.Document, len(documents))
	for _, document := range documents {
		documentIndex[document.ID] = document
	}

	return renderProjectMarkdown(ProjectReport{
		Project: project, Documents: documentIndex, Insights: details,
		Metrics: metrics, GeneratedAt: a.now(),
	}), nil
}

func renderProjectMarkdown(report ProjectReport) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s — Insight Report\n\n", markdownInline(report.Project.Name))
	fmt.Fprintf(&b, "Generated: %s  \n", report.GeneratedAt.UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "Insights: %d\n\n", len(report.Insights))

	if report.Metrics != nil {
		m := report.Metrics
		b.WriteString("## Quality summary\n\n")
		fmt.Fprintf(&b, "- Evidence Coverage: %.0f%%\n", m.EvidenceCoverage*100)
		fmt.Fprintf(&b, "- Trace-backed Insights: %.0f%%\n", m.TraceBackedInsightRate*100)
		fmt.Fprintf(&b, "- Quality Flagged: %.0f%%\n", m.QualityFlaggedInsightRate*100)
		fmt.Fprintf(&b, "- Source-verified observations: %d / %d\n\n", m.GroundedObservations, m.TotalObservationCandidates)
	}

	if len(report.Insights) == 0 {
		b.WriteString("No analyzed insights are available.\n")
		return []byte(b.String())
	}

	b.WriteString("## Insights\n\n")
	for index, detail := range report.Insights {
		i := detail.Insight
		fmt.Fprintf(&b, "### %d. %s\n\n", index+1, markdownInline(i.Title))
		fmt.Fprintf(&b, "**Latent need:** %s\n\n", markdownInline(i.LatentNeed))
		fmt.Fprintf(&b, "**Confidence:** %.0f%%\n\n", i.Confidence*100)
		writeReportField(&b, "Observation", i.Observation)
		writeReportField(&b, "Stated need", i.StatedNeed)
		writeReportField(&b, "Expected behavior", i.Expectation)
		writeReportField(&b, "Surprising deviation", i.SurprisingFact)
		writeReportField(&b, "Rationale", i.Rationale)
		writeReportField(&b, "JTBD", i.JTBD)
		writeReportField(&b, "Product Opportunity", i.ProductOpportunity)
		writeReportField(&b, "Monetization Angle", i.MonetizationAngle)
		writeReportField(&b, "Alternative interpretation", i.AlternativeInterpretation)

		if len(i.QualityFlags) > 0 {
			b.WriteString("**Quality warnings:**\n\n")
			for _, flag := range i.QualityFlags {
				fmt.Fprintf(&b, "- `%s`", flag.Code)
				if flag.Detail != "" {
					fmt.Fprintf(&b, ": %s", markdownInline(flag.Detail))
				}
				b.WriteByte('\n')
			}
			b.WriteByte('\n')
		}

		if len(detail.Evidence) > 0 {
			b.WriteString("**Source-verified evidence:**\n\n")
			for _, evidence := range detail.Evidence {
				label := "support"
				if evidence.Type == domain.EvidenceCounter {
					label = "counter-evidence"
				}
				title := evidence.DocumentID
				if document := report.Documents[evidence.DocumentID]; document != nil && document.Title != "" {
					title = document.Title
				}
				fmt.Fprintf(&b, "- **%s / %s**\n%s\n", label, markdownInline(title), markdownQuote(evidence.Quote))
			}
			b.WriteByte('\n')
		}
	}

	b.WriteString("---\n\nGenerated by Insight Lab. These are AI-generated hypotheses; verify the original evidence before making decisions.\n")
	return []byte(b.String())
}

func writeReportField(b *strings.Builder, label, value string) {
	if strings.TrimSpace(value) != "" {
		fmt.Fprintf(b, "**%s:** %s\n\n", label, markdownInline(value))
	}
}

func markdownInline(value string) string {
	value = strings.Join(strings.Fields(value), " ")
	return strings.NewReplacer("\\", "\\\\", "`", "\\`", "*", "\\*", "_", "\\_", "[", "\\[", "]", "\\]").Replace(value)
}

func markdownQuote(value string) string {
	lines := strings.Split(strings.TrimSpace(value), "\n")
	for i := range lines {
		lines[i] = "> " + lines[i]
	}
	return strings.Join(lines, "\n")
}
