package domain

// CausalStatus describes the strength of a causal claim. It is deliberately
// separate from Confidence, which is only an internal evidence-quality score.
type CausalStatus string

const (
	CausalObservedAssociation CausalStatus = "OBSERVED_ASSOCIATION"
	CausalHypothesis          CausalStatus = "CAUSAL_HYPOTHESIS"
	CausallySupported         CausalStatus = "CAUSALLY_SUPPORTED"
	CausalNotIdentified       CausalStatus = "NOT_IDENTIFIED"
)

type ValidationStatus string

const (
	ValidationUntested             ValidationStatus = "UNTESTED"
	ValidationPlausible            ValidationStatus = "PLAUSIBLE"
	ValidationPartiallySupported   ValidationStatus = "PARTIALLY_SUPPORTED"
	ValidationSupported            ValidationStatus = "SUPPORTED"
	ValidationInsufficientEvidence ValidationStatus = "INSUFFICIENT_EVIDENCE"
	ValidationContradicted         ValidationStatus = "CONTRADICTED"
)

type IdentificationStatus string

const (
	IdentificationIdentified    IdentificationStatus = "IDENTIFIED"
	IdentificationNotIdentified IdentificationStatus = "NOT_IDENTIFIED"
	IdentificationUnknown       IdentificationStatus = "UNKNOWN"
)

// ExpectationBasis records where an Expectation came from (its provenance)
// relative to the data it is later compared against. It answers "was this
// expectation fixed before or after the observed data was available?" and
// "can its origin be traced?", which together decide whether a match between
// expectation and data is a pre-registered check or an exploratory finding.
//
// Provenance is never upgraded. In particular, the post-hoc values below are
// never rewritten as PRIOR; an exploratory expectation reaches validation by
// being carried into a new research iteration as DERIVED_FROM_PRIOR_RUN.
type ExpectationBasis string

const (
	// ExpectationPrior: stated before any of the analysed data was seen.
	ExpectationPrior ExpectationBasis = "PRIOR"
	// ExpectationLiterature: taken from a citable published source.
	ExpectationLiterature ExpectationBasis = "LITERATURE"
	// ExpectationDomainKnowledge: practitioner/domain knowledge with a
	// traceable justification.
	ExpectationDomainKnowledge ExpectationBasis = "DOMAIN_KNOWLEDGE"
	// ExpectationModelProposedPostHoc: generated by a model after it had
	// access to the observed data.
	ExpectationModelProposedPostHoc ExpectationBasis = "MODEL_PROPOSED_POST_HOC"
	// ExpectationHumanPostHoc: written by a human after seeing the data.
	ExpectationHumanPostHoc ExpectationBasis = "HUMAN_POST_HOC"
	// ExpectationDerivedFromPriorRun: carried over from an earlier research
	// iteration so a new iteration can test it on data not yet observed.
	ExpectationDerivedFromPriorRun ExpectationBasis = "DERIVED_FROM_PRIOR_RUN"
	// ExpectationOther: explicitly classified as none of the above.
	ExpectationOther ExpectationBasis = "OTHER"
	// ExpectationUnknown: provenance is missing. It is kept as unknown
	// rather than guessed, and it blocks strong validation claims.
	ExpectationUnknown ExpectationBasis = "UNKNOWN"

	// Legacy values kept for stored data and the current pipeline output.
	// ExpectationModelProposed predates the post-hoc distinction; the model
	// that produced it always had the analysed documents in context, so it
	// normalises to MODEL_PROPOSED_POST_HOC. ExpectationSourceBacked only
	// says the expectation quoted some source; whether that source was seen
	// before the data is unrecorded, so its timing stays unknown.
	ExpectationSourceBacked  ExpectationBasis = "SOURCE_BACKED"
	ExpectationModelProposed ExpectationBasis = "MODEL_PROPOSED"
)

// ObservationTiming states whether an expectation's origin is, by definition,
// before or after the observed data became available.
type ObservationTiming string

const (
	TimingPreObservation  ObservationTiming = "PRE_OBSERVATION"
	TimingPostObservation ObservationTiming = "POST_OBSERVATION"
	TimingUnknown         ObservationTiming = "UNKNOWN"
)

func (b ExpectationBasis) Valid() bool {
	switch b {
	case ExpectationPrior, ExpectationLiterature, ExpectationDomainKnowledge,
		ExpectationModelProposedPostHoc, ExpectationHumanPostHoc, ExpectationDerivedFromPriorRun,
		ExpectationOther, ExpectationUnknown,
		ExpectationSourceBacked, ExpectationModelProposed:
		return true
	}
	return false
}

// Normalize maps legacy and empty values onto the provenance vocabulary. It
// only ever moves a value sideways or towards UNKNOWN; it never turns a
// post-hoc or unknown value into PRIOR.
func (b ExpectationBasis) Normalize() ExpectationBasis {
	switch {
	case b == ExpectationModelProposed:
		return ExpectationModelProposedPostHoc
	case !b.Valid():
		return ExpectationUnknown
	}
	return b
}

// IsPostHoc reports whether the origin implies the observed data had already
// been seen when the expectation was written.
func (b ExpectationBasis) IsPostHoc() bool {
	return b.ObservationTiming() == TimingPostObservation
}

func (b ExpectationBasis) ObservationTiming() ObservationTiming {
	switch b.Normalize() {
	case ExpectationPrior, ExpectationLiterature, ExpectationDomainKnowledge, ExpectationDerivedFromPriorRun:
		return TimingPreObservation
	case ExpectationModelProposedPostHoc, ExpectationHumanPostHoc:
		return TimingPostObservation
	}
	return TimingUnknown
}

// RequiresSourceReference is true for origins whose claim to be pre-observation
// rests on something a reader must be able to follow up.
func (b ExpectationBasis) RequiresSourceReference() bool {
	return b == ExpectationLiterature || b == ExpectationDomainKnowledge
}

// PermitsStrongValidationClaim reports whether an expectation of this origin
// may, once frozen and tested on independent evidence, be reported as a
// validation result rather than an exploratory finding. Post-hoc, unknown,
// other and legacy origins are excluded.
func (b ExpectationBasis) PermitsStrongValidationClaim() bool {
	switch b {
	case ExpectationPrior, ExpectationLiterature, ExpectationDomainKnowledge, ExpectationDerivedFromPriorRun:
		return true
	}
	return false
}

type VariableRole string

const (
	RoleExposure   VariableRole = "EXPOSURE"
	RoleOutcome    VariableRole = "OUTCOME"
	RoleConfounder VariableRole = "CONFOUNDER"
	RoleMediator   VariableRole = "MEDIATOR"
	RoleCollider   VariableRole = "COLLIDER"
	RoleUnknown    VariableRole = "UNKNOWN"
)

type ProposalStatus string

const (
	ProposalProposed  ProposalStatus = "PROPOSED"
	ProposalSupported ProposalStatus = "SUPPORTED"
	ProposalUnknown   ProposalStatus = "UNKNOWN"
)

type CausalVariable struct {
	ID     string         `json:"id"`
	Name   string         `json:"name"`
	Role   VariableRole   `json:"role"`
	Status ProposalStatus `json:"status"`
}

type CausalRelation struct {
	From   string         `json:"from"`
	To     string         `json:"to"`
	Status ProposalStatus `json:"status"`
}

// CandidateCausalStructure is a proposal to inspect, never a discovered or
// proven DAG. In particular, collider variables must not automatically become
// controls.
type CandidateCausalStructure struct {
	Variables []CausalVariable `json:"variables"`
	Relations []CausalRelation `json:"relations"`
}

type CompetingHypothesis struct {
	Title                 string   `json:"title"`
	Explanation           string   `json:"explanation"`
	Rationale             string   `json:"rationale,omitempty"`
	MissingEvidence       []string `json:"missingEvidence,omitempty"`
	FalsificationCriteria []string `json:"falsificationCriteria,omitempty"`
	RequiredData          []string `json:"requiredData,omitempty"`
	RequiredComparisons   []string `json:"requiredComparisons,omitempty"`
	CandidateDesigns      []string `json:"candidateDesigns,omitempty"`
}

type HypothesisRole string

const (
	HypothesisPrimary   HypothesisRole = "PRIMARY"
	HypothesisCompeting HypothesisRole = "COMPETING"
)

type ValidationNeed struct {
	Data       []string `json:"data"`
	Comparison []string `json:"comparison"`
	Design     []string `json:"design"`
}
